services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/habit_tracker?sslmode=disable
      - ALLOWED_ORIGINS=http://localhost:5173,http://localhost:3000,http://frontend:5173
      - PORT=8080

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: habit_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  migrate:
    image: postgres:latest
    volumes:
      - ./infrastructure/db/migrations:/migrations
      - ./run-migrations.sh:/migrations/run-migrations.sh
    entrypoint: ["/bin/sh", "/migrations/run-migrations.sh"]
    depends_on:
      - db

volumes:
  postgres_data: